services:
    _defaults:
        autowire: true
        autoconfigure: true

    Planer\PlanerBundle\:
        resource: '../src/'
        exclude: '../src/{Entity,Model}'

    Planer\PlanerBundle\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Planer\PlanerBundle\Twig\PlanerExtension:
        arguments:
            $baseTemplate: '%planer.base_template%'
            $logoutRoute: '%planer.logout_route%'
            $resolver: '@Planer\PlanerBundle\Service\PlanerUserResolver'
        tags: ['twig.extension']

    Planer\PlanerBundle\Service\PlanerUserResolver:
        arguments:
            $fullNameFields: '%planer.user_full_name_fields%'
