services:
    _defaults:
        autowire: true
        autoconfigure: true

    Planer\PlanerBundle\:
        resource: '../src/'
        exclude: '../src/{Entity,Model}'

    Planer\PlanerBundle\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Planer\PlanerBundle\Twig\PlanerExtension:
        arguments:
            $baseTemplate: '%planer.base_template%'
        tags: ['twig.extension']
